class ExerciseDB {
  static const Map<String, List<String>> categories = {
    'Chest': [
      'Bench Press', 'Incline Bench Press', 'Decline Bench Press',
      'Dumbbell Bench Press', 'Incline Dumbbell Press', 'Decline Dumbbell Press',
      'Chest Fly (Dumbbell)', 'Incline Dumbbell Fly', 'Cable Fly', 'Machine Chest Fly',
      'Incline Cable Fly', 'Cable Crossover', 'Push Ups', 'Decline Push Up',
      'Push Up (Wide Grip)', 'Push Up (Diamond)', 'Push Up (Pike)',
      'Dips (Chest Focus)', 'Machine Chest Press', 'Pec Deck', 'Pec Fly',
      'Converging Chest Press', 'Incline Chest Press', 'Decline Chest Press',
      'Svend Press', 'Guillotine Press', 'Hex Press', 'Spoto Press', 'Floor Press',
    ],
    'Back': [
      'Deadlift', 'Romanian Deadlift', 'Sumo Deadlift', 'Stiff-Leg Deadlift',
      'Trap Bar Deadlift', 'Deficit Deadlift', 'Barbell Row', 'Pendlay Row',
      'Dumbbell Row', 'Seal Row', 'Chest-Supported Row', 'Chest-Supported T-Bar Row',
      'Seated Cable Row', 'Cable Row (Wide Grip)', 'Single-Arm Cable Row',
      'Lat Pulldown', 'Lat Pulldown (Close Grip)', 'Lat Pulldown (Wide Grip)',
      'Lat Pulldown (Underhand)', 'Lat Pulldown (V-Bar)',
      'Straight-Arm Pulldown', 'Pull Ups', 'Chin Ups', 'Neutral Grip Pull Ups',
      'T-Bar Row', 'Back Extension', 'Shrugs', 'Dumbbell Shrugs',
      'Cable Pullover', 'Dumbbell Pullover', 'Renegade Row',
    ],
    'Legs': [
      'Squat', 'Front Squat', 'Box Squat', 'Hack Squat', 'Smith Machine Squat',
      'Goblet Squat', 'Sumo Squat', 'Pistol Squat', 'Sissy Squat', 'Belt Squat',
      'Leg Press', 'Hack Squat Machine', 'Lunges', 'Walking Lunges', 'Reverse Lunge',
      'Bulgarian Split Squat', 'Step Ups',
      'Leg Extension', 'Hamstring Curl', 'Seated Leg Curl', 'Prone Leg Curl', 'Lying Leg Curl', 'Standing Leg Curl',
      'Nordic Hamstring Curl', 'Glute-Ham Raise',
      'Calf Raises', 'Seated Calf Raise', 'Standing Calf Raise', 'Donkey Calf Raise', 'Leg Press Calf Raise',
      'Hip Thrust', 'Glute Bridge', 'Good Mornings', 'Cable Pull Through',
      'Hip Abduction Machine', 'Hip Adduction Machine', 'Cable Kickback',
    ],
    'Shoulders': [
      'Overhead Press', 'Dumbbell Shoulder Press', 'Machine Shoulder Press',
      'Converging Shoulder Press', 'Plate-Loaded Shoulder Press',
      'Arnold Press', 'Push Press', 'Behind-the-Neck Press', 'Bradford Press',
      'Lateral Raises', 'Cable Lateral Raise', 'Bent-Over Lateral Raise',
      'Machine Lateral Raise', 'Front Raises', 'Cable Front Raise', 'Dumbbell Front Raise',
      'Rear Delt Fly', 'Rear Delt Fly (Dumbbell)', 'Cable Reverse Fly', 'Reverse Pec Deck Fly',
      'Upright Row', 'Cable Upright Row', 'Barbell Upright Row', 'Face Pulls', 'Handstand Push-up',
    ],
    'Arms': [
      'Bicep Curl (Barbell)', 'Bicep Curl (Dumbbell)', 'Bicep Curl Machine',
      'Hammer Curl', 'Rope Hammer Curl', 'Preacher Curl', 'Preacher Curl Machine',
      'Concentration Curl', 'EZ Bar Curl', 'Spider Curl', 'Zottman Curl',
      'Incline Curl', 'Cable Curl', 'Cable Curl (Single Arm)',
      'Overhead Cable Curl', 'Reverse Curl',
      'Tricep Pushdown', 'Tricep Pushdown (Bar)', 'Tricep Rope Pushdown', 'Cable Pushdown',
      'Tricep Extension', 'Tricep Extension (Cable)', 'Tricep Extension (Dumbbell)',
      'Skull Crushers', 'Overhead Tricep Extension', 'Overhead Cable Extension',
      'Close Grip Bench Press', 'Tricep Extension Machine', 'Dip Machine',
      'Tricep Dips', 'Bench Dips', 'JM Press', 'Tate Press', 'Kickbacks',
      'Wrist Roller', 'Wrist Curls', 'Reverse Wrist Curls',
    ],
    'Core': [
      'Plank', 'Side Plank', 'Crunches', 'Bicycle Crunches', 'Decline Crunch',
      'Abdominal Crunch', 'Weighted Crunch', 'Ab Machine',
      'Leg Raises', 'Hanging Knee Raises', 'Hanging Leg Raises', 'Roman Chair Leg Raises',
      'Knee Raise (Parallel Bars)', 'Leg Raise (Parallel Bars)',
      'Russian Twist', 'Cable Crunch', 'Ab Wheel Rollout',
      'Leg Raises (Captain Chair)', 'Mountain Climbers',
      'Dragon Flag', 'Hollow Body Hold', 'Dead Bug', 'Cable Woodchopper',
      'V-Ups', 'Windshield Wipers', 'Pallof Press', 'Flutter Kicks', 'Plank Jacks',
    ],
    'Full Body': [
      'Clean and Jerk', 'Power Clean', 'Hang Clean', 'Hang Power Clean',
      'Snatch', 'Power Snatch', 'Push Jerk', 'Split Jerk',
      'Thruster', 'Turkish Get-up',
      "Farmer's Carry", 'Suitcase Carry', 'Overhead Carry',
      'Bear Crawl', 'Sandbag Carry', 'Sled Push', 'Sled Pull',
      'Battle Ropes', 'Med Ball Slam', 'Tire Flip', 'Muscle Up',
    ],
    'Cardio': [
      'Treadmill Run', 'Walking', 'Walking (Slow)', 'Walking (Brisk)', 'Walking (Incline)',
      'Outdoor Run', 'Trail Run',
      'Cycling (Stationary)', 'Cycling (Outdoor)', 'Assault Bike', 'Spin Bike', 'Air Bike',
      'Rowing Machine', 'Elliptical', 'Stair Climber', 'SkiErg', 'Cross-Trainer',
      'Jump Rope', 'Swimming', 'Pool Swimming', 'Open Water Swimming',
      'HIIT Session', 'Sprint Intervals',
      'Burpees', 'Kettlebell Swing', 'Box Jumps', 'Broad Jump',
    ],
  };

  static List<String> get allExercises =>
      categories.values.expand((e) => e).toList();
}
